version: 2.1

jobs:
  build:
    docker:
      - image: sanjeevandocker/webapp

    steps:
      - checkout

      - run:
          name: Build and test
          command: |
            docker build -t sanjeevandocker/webapp -f Dockerfile.dev .
            docker run -e CI=true sanjeevandocker/webapp npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
