sudo: require
services:
  - docker

before_install:
  - docker build -t sanjeevandocker/webapp -f Dockerfile.dev .
  
script:
  - docker run -e CI=true sanjeevandocker/webapp npm run test -- --coverage